FROM arm64v8/python:3.7-slim-buster

# Install Python packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app

# Expose the port
EXPOSE 80

# Set the working directory
WORKDIR /app

# Run the flask server for the endpoints
CMD python -u app.py