FROM amd64/python:3.7-slim-buster

RUN apt-get update && \
# required for opencv
apt-get -y install --no-install-recommends \
    # GUI required by openCV
    libgl1-mesa-glx libgtk2.0-dev \
    # Hierarchical Data Format
    libhdf5-dev libhdf5-serial-dev \
    # for image files
    libjpeg-dev libtiff5-dev libpng-dev \
    # for video files
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    # high def image processing
    libilmbase-dev libopenexr-dev

WORKDIR /app

RUN pip install debugpy
# Install Python packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ADD /app/ .
ADD /test/ .

# test environment
ENV VIDEO_PATH "./AppleAndBanana.mp4"
ENV IMAGE_PROCESSING_ENDPOINT "http://127.0.0.1:80/image"
ENV VERBOSE "True"
ENV RESIZE_WIDTH "256"
ENV RESIZE_HEIGHT "256"
ENV SHOW_VIDEO "False"
ENV EdgeHubConnectionString "HostName=testhomehub.azure-devices.net;GatewayHostName=home5-pc.tampabay.rr.com;DeviceId=URPI4_3;ModuleId=target;SharedAccessKey=JPbUkVmlrEj3SoiUgLIDfLxb/a3W4VWKCJ86CnjUgXk="
ENV EdgeModuleCACertificateFile "./edge-device-ca.cert.pem"

# Expose the port
EXPOSE 5012
EXPOSE 5678

ENTRYPOINT [ "python", "-u", "./main.py" ]
